---
abstract: 'Opinionated Modern Perl Development Framework'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bubblegum
requires:
  Class::Forward: 0.100006
  Class::Load: 0
  DateTime::Tiny: 1.04
  Exception::Tiny: 0
  Exporter::Tiny: 0.030
  File::Find::Rule: 0
  File::HomeDir: 1.00
  File::Which: 1.09
  Import::Into: 1.001001
  JSON::Tiny: 0.38
  Module::Find: 0.11
  Moo: 1.003001
  Path::Tiny: 0.047
  Syntax::Keyword::Junction: 0.003007
  Time::Format: 1.12
  Time::ParseDate: 2013.1113
  Try::Tiny: 0.18
  Type::Tiny: 0.032
  YAML::Tiny: 1.56
  autobox: 0
  autodie: 0
  perl: v5.10.0
  utf8::all: 0
resources:
  bugtracker: https://github.com/alnewkirk/Bubblegum/issues
  homepage: http://search.cpan.org/dist/Bubblegum/
  repository: git://github.com/alnewkirk/Bubblegum.git
version: 0.07
x_authority: cpan:AWNCORP
