use Bubblegum::Object::Array;
use Test::More;

can_ok 'Bubblegum::Object::Array', 'all';
can_ok 'Bubblegum::Object::Array', 'any';
can_ok 'Bubblegum::Object::Array', 'count';
can_ok 'Bubblegum::Object::Array', 'defined';
can_ok 'Bubblegum::Object::Array', 'delete';
can_ok 'Bubblegum::Object::Array', 'each';
can_ok 'Bubblegum::Object::Array', 'each_key';
can_ok 'Bubblegum::Object::Array', 'each_n_values';
can_ok 'Bubblegum::Object::Array', 'each_value';
can_ok 'Bubblegum::Object::Array', 'empty';
can_ok 'Bubblegum::Object::Array', 'exists';
can_ok 'Bubblegum::Object::Array', 'first';
can_ok 'Bubblegum::Object::Array', 'get';
can_ok 'Bubblegum::Object::Array', 'grep';
can_ok 'Bubblegum::Object::Array', 'head';
can_ok 'Bubblegum::Object::Array', 'iterator';
can_ok 'Bubblegum::Object::Array', 'join';
can_ok 'Bubblegum::Object::Array', 'keyed';
can_ok 'Bubblegum::Object::Array', 'keys';
can_ok 'Bubblegum::Object::Array', 'last';
can_ok 'Bubblegum::Object::Array', 'length';
can_ok 'Bubblegum::Object::Array', 'list';
can_ok 'Bubblegum::Object::Array', 'map';
can_ok 'Bubblegum::Object::Array', 'max';
can_ok 'Bubblegum::Object::Array', 'min';
can_ok 'Bubblegum::Object::Array', 'none';
can_ok 'Bubblegum::Object::Array', 'nsort';
can_ok 'Bubblegum::Object::Array', 'one';
can_ok 'Bubblegum::Object::Array', 'pairs';
can_ok 'Bubblegum::Object::Array', 'pairs_array';
can_ok 'Bubblegum::Object::Array', 'pairs_hash';
can_ok 'Bubblegum::Object::Array', 'pop';
can_ok 'Bubblegum::Object::Array', 'push';
can_ok 'Bubblegum::Object::Array', 'random';
can_ok 'Bubblegum::Object::Array', 'reverse';
can_ok 'Bubblegum::Object::Array', 'rotate';
can_ok 'Bubblegum::Object::Array', 'rnsort';
can_ok 'Bubblegum::Object::Array', 'rsort';
can_ok 'Bubblegum::Object::Array', 'set';
can_ok 'Bubblegum::Object::Array', 'shift';
can_ok 'Bubblegum::Object::Array', 'size';
can_ok 'Bubblegum::Object::Array', 'slice';
can_ok 'Bubblegum::Object::Array', 'sort';
can_ok 'Bubblegum::Object::Array', 'sum';
can_ok 'Bubblegum::Object::Array', 'tail';
can_ok 'Bubblegum::Object::Array', 'unique';
can_ok 'Bubblegum::Object::Array', 'unshift';
can_ok 'Bubblegum::Object::Array', 'values';

done_testing;
